// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/generic'
// import './example/class'
// import './example/enum'
// import './example/inference'
// import './example/advance-type/1'
// import './example/advance-type/2'
// import './example/advance-type/3'
// import './example/advance-type/4'
import './example/advance-type/5'

const num: number = 111
